[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
color-eyre = "0.6.3"

[dev-dependencies]
testcontainers-modules = { version = "0.9.0", features = ["minio", "postgres", "redis"] }
